DF_GAMEPASS_SRC = '../data/games_gamepass.csv'
DF_METACRITIC_SRC = '../data/games_metacritic.csv'
GAMERS = 'GAMERS'
TIME = 'TIME'
RATIO = 'RATIO'
TRUE_ACHIVEMENTS = 'True_Achievement'
GAME_SCORE = 'Game_Score'